### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by c-kr** [its-lab/MoniTutor-docker#4]
Hi Mark,

we are still trying to get monitutor running. This time within a docker environment.

First we had to rebuild the ms42q/web2py-apache2 image, as debian:stable now refers to buster, but this image was build for stretch.

Secondly, after all containers were running, we are missing the part where icinga2 and the depedencies (web2 & api) are configured. The corresponding readme was removed:

https://github.com/its-lab/MoniTutor/commit/fe827bbf0216a06607b753c3ad8ad93c6a714206#diff-04c6e90faac2675aa89e2176d2eec7d8

Isn't this needed anymore? Any help would be appreciate.

**Comment by ms42Q** [comment]
Hey @c-kr,
The project is still used in production so it will be maintained. It reached a state that is stable in the environment which it's used in so there haven't been any updates in a while. I should update the ms42q/web2py-apache2 image though :innocent:
I will do that as soon as I can.

Instead of the master branch I'd use the couchdb branch which adds a lot of nice features.

https://github.com/its-lab/MoniTutor-docker/tree/chouchDB

This new setup doesn't use icinga anymore and it runs a lot faster and stable.
I'll add some more info to this issue as soon as I have a chance. Today I'm super busy with some other projects.

**Comment by ms42Q** [comment]
There is also a branch db-redesign in the MoniTutor repo. I think you can also use that one instead of master.

git clon

```
git clone https://github.com/its-lab/MoniTutor-docker.git
cd MoniTutor-docker
git checkout couchDB
git submodule update --init --recursive
cd monitutor
cd MoniTutor
git checkout db-redesign
```

and then do a `docker-compose build && docker-compose up` after editing the options

**Comment by ms42Q** [comment]
I updated a bunch of things. There was a bug in one of the libs that i fixed in 
https://github.com/its-lab/MoniTutor-Tunnel/commit/cce1326c8a60eac66d5774c3d98e587ebaa9a9dc

I also upgraded the web2py docker image on dockerhub. There is now a v1.2 version of the image with debian:latest and web2py 2.17.1

https://hub.docker.com/layers/ms42q/web2py-apache2/v1.2/images/sha256-e124350f7f8f8d5ed78a0784ae469ea9eb2908b12da93e50921c345f6ef79022

You should be fine with running 
```
git clone https://github.com/its-lab/MoniTutor-docker.git
git checkout chouchDB   # There is a typo in the branch name :facepalm:
git submodule update --init --recursive
cd compose-monitutor
docker-compose build
docker-compose up
```

Happy hacking!

**Comment by c-kr** [comment]
Thanks mark, we'll try it out
